const { textToTokens } = require('../../src/pipeline/text-to-tokens')

describe('text-to-tokens', () => {
  it('trivial text', async () => {
    expect(textToTokens('Lorem ipsum dolor sit amet.')).toEqual(['Lorem', 'ipsum', 'dolor', 'sit', 'amet'])
  })

  it('realistic issue', async () => {
    expect(textToTokens(`Something went wrong ### What happened?
We have a select query where we are trying to do a deep read into an association.
Here is the query.
CqnSelect select = Select.from(Foo.class)
.columns(daily -> daily._all(), daily -> daily.locations().expand())
.orderBy(getOrderBy(viewName));
Here are the entity files.
----------------------------------------------------------------------------------------------------------------------------
view FooView as select from Bar
{
key bla,
as bar
};
And the error says Invalid column BAR. We checked our view schema as well this column is not available in our schema. Not sure how the column name is getting generated like this.
<img width="452" alt="image" src="https://media.github.tools.example.com/bar">
### Steps to reproduce
Just a normal run will give this issue.
### Versions
| bar | <Add your repository here> |
|:---------------------- | ----------- |
|        | -- missing  |
| @bar/baz      | 4.5.0       |
### OS / Environment
Cloud Foundry
### Relevant log output
com.example.services.impl.ContextualizedFooException: Error executing the statement (service 'PersistenceService$Default', event 'READ', entity 'PrivateDownloadService.fooDailyForDownload')
at com.example.services.impl.ServiceImpl.dispatch(ServiceImpl.java:256)
at com.example.services.impl.ServiceImpl.lambda$dispatchInChangeSetContext$2(ServiceImpl.java:203)
Caused by: com.example.FooDataStoreException: Error executing the statement
at com.example.impl.ExceptionHandler.dataStoreException(ExceptionHandler.java:62)
at com.example.impl.JDBCClient.executeQuery(JDBCClient.java:211)
Caused by: com.example.FooDataStoreException: SQL: SELECT NULLS FIRST
Caused by: com.example.db.jdbc.exceptions.JDBCDriverException:  DBTech JDBC: [260]: invalid column name: T0.MY_VIEW_MY_VIEW_ID: line 1 col 382 (at pos 381)
at com.example.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:209)
at com.example.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42)`)).toEqual([
      "Something",
      "went",
      "wrong",
      "What",
      "happened",
      "We",
      "have",
      "a",
      "select",
      "query",
      "where",
      "we",
      "are",
      "trying",
      "to",
      "do",
      "a",
      "deep",
      "read",
      "into",
      "an",
      "association",
      "Here",
      "is",
      "the",
      "query",
      "CqnSelect",
      "select",
      "Select",
      "from",
      "Foo",
      "class",
      "columns",
      "daily",
      "daily",
      "_all",
      "daily",
      "daily",
      "locations",
      "expand",
      "orderBy",
      "getOrderBy",
      "viewName",
      "Here",
      "are",
      "the",
      "entity",
      "files",
      "view",
      "FooView",
      "as",
      "select",
      "from",
      "Bar",
      "key",
      "bla",
      "as",
      "bar",
      "And",
      "the",
      "error",
      "says",
      "Invalid",
      "column",
      "BAR",
      "We",
      "checked",
      "our",
      "view",
      "schema",
      "as",
      "well",
      "this",
      "column",
      "is",
      "not",
      "available",
      "in",
      "our",
      "schema",
      "Not",
      "sure",
      "how",
      "the",
      "column",
      "name",
      "is",
      "getting",
      "generated",
      "like",
      "this",
      "img",
      "width",
      "452",
      "alt",
      "image",
      "src",
      "https",
      "media",
      "github",
      "tools",
      "example",
      "com",
      "bar",
      "Steps",
      "to",
      "reproduce",
      "Just",
      "a",
      "normal",
      "run",
      "will",
      "give",
      "this",
      "issue",
      "Versions",
      "bar",
      "Add",
      "your",
      "repository",
      "here",
      "missing",
      "bar",
      "baz",
      "4",
      "5",
      "0",
      "OS",
      "Environment",
      "Cloud",
      "Foundry",
      "Relevant",
      "log",
      "output",
      "com",
      "example",
      "services",
      "impl",
      "ContextualizedFooException",
      "Error",
      "executing",
      "the",
      "statement",
      "service",
      "PersistenceService",
      "Default",
      "event",
      "READ",
      "entity",
      "PrivateDownloadService",
      "fooDailyForDownload",
      "at",
      "com",
      "example",
      "services",
      "impl",
      "ServiceImpl",
      "dispatch",
      "ServiceImpl",
      "java",
      "256",
      "at",
      "com",
      "example",
      "services",
      "impl",
      "ServiceImpl",
      "lambda",
      "dispatchInChangeSetContext",
      "2",
      "ServiceImpl",
      "java",
      "203",
      "Caused",
      "by",
      "com",
      "example",
      "FooDataStoreException",
      "Error",
      "executing",
      "the",
      "statement",
      "at",
      "com",
      "example",
      "impl",
      "ExceptionHandler",
      "dataStoreException",
      "ExceptionHandler",
      "java",
      "62",
      "at",
      "com",
      "example",
      "impl",
      "JDBCClient",
      "executeQuery",
      "JDBCClient",
      "java",
      "211",
      "Caused",
      "by",
      "com",
      "example",
      "FooDataStoreException",
      "SQL",
      "SELECT",
      "NULLS",
      "FIRST",
      "Caused",
      "by",
      "com",
      "example",
      "db",
      "jdbc",
      "exceptions",
      "JDBCDriverException",
      "DBTech",
      "JDBC",
      "260",
      "invalid",
      "column",
      "name",
      "T0",
      "MY_VIEW_MY_VIEW_ID",
      "line",
      "1",
      "col",
      "382",
      "at",
      "pos",
      "381",
      "at",
      "com",
      "example",
      "db",
      "jdbc",
      "exceptions",
      "SQLExceptionSapDB",
      "_newInstance",
      "SQLExceptionSapDB",
      "java",
      "209",
      "at",
      "com",
      "example",
      "db",
      "jdbc",
      "exceptions",
      "SQLExceptionSapDB",
      "newInstance",
      "SQLExceptionSapDB",
      "java",
      "42"
    ])
  })
})
